name: h-manhunt
version: '${project.version}'
main: me.matistan05.minecraftmanhunt.Main
api-version: 1.21
authors: [hetashi, Matistan05]
description: Enhanced fork of MinecraftManhunt by hetashi
commands:
  manhunt:
    description: This command sets up the whole manhunt game
    usage: /<command>
permissions:
  manhunt.manhunt:
    description: Allows the player to use all /manhunt commands
    children:
      manhunt.add: true
      manhunt.remove: true
      manhunt.start: true
      manhunt.reset: true
      manhunt.pause: true
      manhunt.unpause: true
      manhunt.list: true
      manhunt.rules: true
      manhunt.help: true
      manhunt.update: true
      manhunt.worlds: true
  manhunt.update:
    description: Allows the player to check and download plugin updates
  manhunt.worlds:
    description: Allows the player to manage prepared match worlds
